disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - explicit_init
  - force_unwrapping
  - implicitly_unwrapped_optional

included:
  - Nutris

excluded:
  - Pods
  - DerivedData

line_length:
  warning: 120
  error: 150

function_body_length:
  warning: 40
  error: 60

file_length:
  warning: 400
  error: 600

identifier_name:
  min_length: 3

type_body_length:
  warning: 200
  error: 300
